export const socialLinks = [
  {
    id: "discord",
    name: "Discord",
    icon: "👾",
    username: "alexchen#1234",
    color: "bg-indigo-500",
    textColor: "text-indigo-500",
    link: "https://discord.com/users/alexchen",
  },
  {
    id: "bilibili",
    name: "Bilibili",
    icon: "📺",
    username: "Alex_创意空间",
    color: "bg-pink-500",
    textColor: "text-pink-500",
    link: "https://bilibili.com/alexchen",
  },
  {
    id: "github",
    name: "GitHub",
    icon: "💻",
    username: "alex-chen",
    color: "bg-gray-800",
    textColor: "text-gray-800 dark:text-gray-300",
    link: "https://github.com/alexchen",
  },
  {
    id: "email",
    name: "Email",
    icon: "✉️",
    username: "alex@example.com",
    color: "bg-blue-500",
    textColor: "text-blue-500",
    link: "mailto:alex@example.com",
  },
  {
    id: "qq",
    name: "QQ",
    icon: "🐧",
    username: "123456789",
    color: "bg-cyan-500",
    textColor: "text-cyan-500",
    link: "https://example.com/qq",
  },
  {
    id: "telegram",
    name: "Telegram",
    icon: "📱",
    username: "@alexchen",
    color: "bg-sky-500",
    textColor: "text-sky-500",
    link: "https://t.me/alexchen",
  },
]; 